using System.Threading.Tasks;
using App.Develop.AppServices.Auth;
using App.Develop.AppServices.Firebase;
using App.Develop.AppServices.Firebase.Auth;
using App.Develop.CommonServices.AssetManagement;
using App.Develop.CommonServices.ConfigsManagement;
using App.Develop.CommonServices.CoroutinePerformer;
using App.Develop.CommonServices.DataManagement;
using App.Develop.CommonServices.DataManagement.DataProviders;
using App.Develop.CommonServices.Emotion;
using App.Develop.CommonServices.LoadingScreen;
using App.Develop.CommonServices.SceneManagement;
using App.Develop.CommonServices.UI;
using App.Develop.DI;
using App.Develop.Scenes.PersonalAreaScene;
using Firebase;
using UnityEngine;

namespace App.Develop.EntryPoint
{
    public class EntryPoint : MonoBehaviour
    {
        [SerializeField] private Bootstrap _appBootstrap;
        private DIContainer _projectContainer;

        private async void Start()
        {
            SetupAppSettings();

            _projectContainer = new DIContainer();
            
            RegisterCoreServices();
            RegisterPersonalAreaServices();

            _projectContainer.Initialize();
            _projectContainer.Resolve<PlayerDataProvider>().Load();

            if (await InitFirebaseAsync())
            {
                _projectContainer.Resolve<ICoroutinePerformer>()
                    .StartPerformCoroutine(_appBootstrap.Run(_projectContainer));
            }
            else
            {
                Debug.LogError("‚ùå Firebase –Ω–µ –≥–æ—Ç–æ–≤. –ü—Ä–∏–ª–æ–∂–µ–Ω–∏–µ –Ω–µ –º–æ–∂–µ—Ç –ø—Ä–æ–¥–æ–ª–∂–∏—Ç—å —Ä–∞–±–æ—Ç—É.");
            }
        }

        private void RegisterPersonalAreaServices()
        {
            _projectContainer.RegisterAsSingle<IPersonalAreaService>(di =>
                new PersonalAreaService(
                    di.Resolve<EmotionService>()
                )
            );
        }

        private void SetupAppSettings()
        {
            QualitySettings.vSyncCount = 0;
            Application.targetFrameRate = 60;
        }

        private async Task<bool> InitFirebaseAsync()
        {
            var task = FirebaseApp.CheckAndFixDependenciesAsync();
            await task;
            return task.Result == DependencyStatus.Available;
        }

        private void RegisterCoreServices()
        {
            // –ë–∞–∑–æ–≤—ã–µ —Å–µ—Ä–≤–∏—Å—ã
            _projectContainer.RegisterAsSingle<ResourcesAssetLoader>(_ => new ResourcesAssetLoader());
            
            // –°–µ—Ä–≤–∏—Å—ã –¥–ª—è —Ä–∞–±–æ—Ç—ã —Å –¥–∞–Ω–Ω—ã–º–∏
            _projectContainer.RegisterAsSingle<ISaveLoadService>(_ =>
                new SaveLoadService(new JsonSerializer(), new LocalDataRepository()));

            _projectContainer.RegisterAsSingle(di =>
                new ConfigsProviderService(di.Resolve<ResourcesAssetLoader>())
            );

            // Firebase —Å–µ—Ä–≤–∏—Å—ã
            _projectContainer.RegisterAsSingle<FirebaseManager>(_ => new FirebaseManager());
            _projectContainer.RegisterAsSingle<ValidationService>(_ => new ValidationService());
            _projectContainer.RegisterAsSingle(_ => new CredentialStorage("UltraSecretKey!üî•"));
            _projectContainer.RegisterAsSingle(di => new AuthService(di.Resolve<FirebaseManager>()));
            _projectContainer.RegisterAsSingle(di => new UserProfileService(di.Resolve<FirebaseManager>()));

            // –°–µ—Ä–≤–∏—Å—ã –¥–ª—è —Ä–∞–±–æ—Ç—ã —Å –¥–∞–Ω–Ω—ã–º–∏ –∏–≥—Ä–æ–∫–∞
            _projectContainer.RegisterAsSingle(di =>
                new PlayerDataProvider(
                    di.Resolve<ISaveLoadService>(),
                    di.Resolve<ConfigsProviderService>()
                )
            );

            _projectContainer.RegisterAsSingle(di => new EmotionService(di.Resolve<PlayerDataProvider>()));
            _projectContainer.RegisterAsSingle(di => new PersonalAreaService(di.Resolve<EmotionService>()));

            // UI –∏ —Å—Ü–µ–Ω–æ–≤—ã–µ —Å–µ—Ä–≤–∏—Å—ã
            _projectContainer.RegisterAsSingle<ICoroutinePerformer>(di =>
                Instantiate(di.Resolve<ResourcesAssetLoader>().LoadResource<CoroutinePerformer>(AssetPaths.CoroutinePerformer))
            );

            _projectContainer.RegisterAsSingle<ILoadingScreen>(di =>
                Instantiate(di.Resolve<ResourcesAssetLoader>().LoadResource<LoadingScreen>(AssetPaths.LoadingScreen))
            );

            _projectContainer.RegisterAsSingle<ISceneLoader>(_ => new SceneLoader());

            _projectContainer.RegisterAsSingle(di =>
                new SceneSwitcher(
                    di.Resolve<ICoroutinePerformer>(),
                    di.Resolve<ILoadingScreen>(),
                    di.Resolve<ISceneLoader>(),
                    di
                )
            );

            _projectContainer.RegisterAsSingle(di =>
                new PanelManager(
                    di.Resolve<ResourcesAssetLoader>(),
                    new MonoFactory(di)
                )
            );
        }

        private void OnDestroy()
        {
            _projectContainer?.Dispose();
        }
    }
}